diary/routes.py
from flask import Blueprint, request, redirect, session, render_template, flash, send_file
from flask_session import Session
from werkzeug.security import check_password_hash, generate_password_hash
from werkzeug.exceptions import default_exceptions, HTTPException, InternalServerError
from helpers import apology, login_required, error_page, connectdb


diary = Blueprint('diary', __name__)

db = connectdb()


@diary.route('/add_diary', methods=['POST'])
@login_required
def add_diary():
    diary = request.form.get('diary')
    date = request.form.get('today_date')
    rating = request.form.get('rating')
    title = request.form.get('title')
    if not (diary and date and rating):
        return apology('please fill the form')
    if not title:
        title = 'Untitled'
    diaries_dates = db.execute('SELECT date FROM diaries WHERE user_id = :id AND date >= :date',
                               {'id': session['user_id'], 'date': date}).fetchall()
    if diaries_dates:
        return error_page('You already wrote a diary for today.')
    db.execute('INSERT INTO diaries (user_id, diary, date, title, rating) VALUES (:id, :diary, :date, :title, :rating)',
               {'id': session['user_id'], 'diary': diary, 'date': date, 'title': title, 'rating': rating})
    db.commit()
    flash('Diary Added!')
    return redirect(f"/diaries/{session['username']}/{date}")


@diary.route('/diaries/<username>/<date>')
@login_required
def diary_page(username, date):
    """Shows a diary"""

    if username == session['username']:
        diary = db.execute('SELECT * FROM diaries WHERE user_id = :id AND date = :date', {'id': session['user_id'], 'date': date}).fetchone()
        if diary:
            return render_template('diary_page.html', diary=diary, username=session['username'])
        else:
            return error_page("Diary doesn't exist")
    else:
        visibility = db.execute('SELECT visibility FROM users WHERE username = :username', {'username': username}).fetchone()
        if not visibility or visibility[0] == '0':
            return error_page("Access denied or user doesn't exist.")
        else:
            diary = db.execute("""SELECT * FROM diaries JOIN users ON diaries.user_id = users.id WHERE users.username = :username AND date = :date""", 
                                {'username': session['username'], 'date': date}).fetchone()
            return render_template('diary_page.html', diary=diary, username=username)
    

@diary.route('/download', methods=['POST'])
@login_required
def download_diary():
    username = request.form.get('username')
    date = request.form.get('date')
    if not (username and date):
        return apology('something went wrong')
    info = db.execute('SELECT id, visibility FROM users WHERE username = :username', {'username': username}).fetchone()
    if not info:
        return error_page("User doesn't exist")
    if username != session['username'] and info['visibility'] == '0':
        return error_page("This user's diaries are private or user doesn't exist")
    diary = db.execute('SELECT * FROM diaries WHERE user_id = :id AND date = :date', {'id': info['id'], 'date': date}).fetchone()
    if not diary:
        return error_page("Diary doesn't exist")
    with open('diary.md', 'w') as d:
        header = f"{diary['title']}\nby {username}.\n{diary['date']}\nThat day was {diary['rating']}.\n"
        d.write(header)
        d.write(diary['diary'])
    return send_file('diary.md', as_attachment=True)


@diary.route('/public_diaries')
@login_required
def public_diaries():
    diaries = db.execute("""SELECT title, rating, diary, date, username 
                            FROM diaries JOIN users ON diaries.user_id = users.id
                            WHERE users.visibility = '1' ORDER BY date DESC""").fetchall()
    return render_template('public_diaries.html', diaries=diaries)


def errorhandler(e):
    """Handle error"""
    if not isinstance(e, HTTPException):
        e = InternalServerError()
    return apology(e.name, e.code)


# Listen for errors
for code in default_exceptions:
    diary.errorhandler(code)(errorhandler)

settings/routes.py
from flask import Blueprint, request, render_template, flash, url_for
from flask_session import Session
from werkzeug.security import check_password_hash, generate_password_hash
from werkzeug.exceptions import default_exceptions, HTTPException, InternalServerError
from helpers import *


settings = Blueprint('settings', __name__)

db = connectdb()


@settings.route("/settings/change_visibility")
@login_required
def change_visibility():
    visibility = db.execute('SELECT visibility FROM users WHERE id = :id', {'id': session['user_id']}).fetchone()[0]
    if visibility == '0':
        visibility = '1'
    else:
        visibility = '0'
    db.execute('UPDATE users SET visibility = :visibility WHERE id = :id', {'id': session['user_id'], 'visibility': visibility})
    db.commit()
    flash('Visibility Changed!')
    return redirect(url_for('profile', username=session['username']))


@settings.route("/settings/change_password", methods=["GET", "POST"])
@login_required
def change_password():
    if request.method == "GET":
        return render_template("change_password.html")
    else:
        password = request.form.get("password")
        new_password = request.form.get("new_password")
        confirmation = request.form.get("confirmation")
        pw_hash = db.execute("SELECT hash FROM users WHERE id = :id", {"id": session["user_id"]}).fetchone()["hash"]
        if not password or not new_password or new_password != confirmation:
            return apology("please fill the form correctly")
        elif password == new_password:
            return apology("new and old password can't be the same")
        elif not check_password_hash(pw_hash, password):
            return apology("incorrect password")
        else:
            # Specifications for password
            # password length
            if len(new_password) < 6:
                return apology("password must be longer than 6 characters")
            capital = None
            lower = None
            for c in new_password:
                if c.isupper():
                    capital = True
                if c.islower():
                    lower = True
            if not capital and not lower:
                return apology("password must contain atleast 1 uppercase and lowercase letter")
            # password must contain numbers
            if new_password.isalpha():
                return apology("password must contain numbers")
            # password must contain letters
            if new_password.isdigit():
                return apology("password must contain letters")
            db.execute("UPDATE users SET hash = :new_password WHERE id = :id",
                       {"new_password": generate_password_hash(new_password), "id": session["user_id"]})
            db.commit()
            flash("Password updated!")
            return redirect("/")


@settings.route("/settings/change_email", methods=["GET", "POST"])
@login_required
def change_email():
    if request.method == "GET":
        return render_template("change_email.html")
    else:
        email = request.form.get("email")
        new_email = request.form.get("new_email")
        if not email or not new_email:
            return apology("please fill the form")
        emails = db.execute("SELECT email FROM users WHERE email = :email", {"email": new_email}).fetchone()
        if email != session["email"]:
            return apology("wrong email")
        if emails:
            return apology("email already taken")
        else:
            db.execute("UPDATE users SET email = :new_email WHERE id = :id",
                       {"new_email": new_email, "id": session["user_id"]})
            db.commit()
            session["email"] = new_email
            flash("Email updated!")
            return redirect("/")


@settings.route("/settings/add_email", methods=["GET", "POST"])
@login_required
def add_email():
    if request.method == "GET":
        return render_template("add_email.html")
    else:
        email = request.form.get("email")
        if not email:
            return apology("please enter an email")
        q = db.execute("SELECT email FROM users WHERE email = :email", {"email": email}).fetchone()
        if q:
            return apology("this email already exists")
        db.execute("UPDATE users SET email = :new_email WHERE id = :id",
                   {"new_email": email, "id": session["user_id"]})
        db.commit()
        session["email"] = email
        flash("Email added!")
        return redirect("/")


@settings.route("/feedback", methods=["GET", "POST"])
def feedback():
    """Get user feedback"""

    if request.method == "GET":
        return render_template("feedback.html")
    else:
        feedback_type = request.form.get("type")
        email = request.form.get("email")
        feedback = request.form.get("feedback")
        if not (feedback_type or email or feedback):
            return apology("please fill the form")
        db.execute("INSERT INTO feedback (user_id, email, feedback, feedback_type) VALUES(:id, :email, :feedback, :type)",
                   {"id": session["user_id"], "email": email, "feedback": feedback, "type": feedback_type})
        db.commit()
        flash("Feedback submitted! Thanks for your feedback!")
        return redirect("/")


def errorhandler(e):
    """Handle error"""
    if not isinstance(e, HTTPException):
        e = InternalServerError()
    return apology(e.name, e.code)


# Listen for errors
for code in default_exceptions:
    settings.errorhandler(code)(errorhandler)

templates/apology.html
{% extends "layout.html" %}

{% block title %}
    Apology
{% endblock %}

{% block main %}
    <img alt="{{ top }}" class="border" src="http://memegen.link/custom/{{ top | urlencode }}/{{ bottom | urlencode }}.jpg?alt=https://i.imgur.com/CsCgN7Ll.png" title="{{ top }}">
{% endblock %}

templates/change_email.html
{% extends "layout.html" %}

{% block title %}
    Change Email
{% endblock %}

{% block main %}

    <form class="needs-validation" novalidate  action="/settings/change_email" autocomplete="off" method="post">
        <div class="form-group">
            <input type="email" autofocus class="form-control small-form" placeholder="Email"id="email" name="email" required>
            <div class="invalid-feedback">Please enter your email</div>
        </div>
        <div class="form-group">
            <input type="email" autofocus class="form-control small-form" placeholder=" New Email"id="new_email" name="new_email" required>
            <div class="invalid-feedback">Please enter your new email</div>
        </div>
        <button class="btn btn-primary" type="submit">Change</button>
    </form>
{% endblock %}

templates/change_password.html
{% extends "layout.html" %}

{% block title %}
    Change Password
{% endblock %}

{% block main %}

    <form class="needs-validation" id="form" novalidate  action="/settings/change_password" autocomplete="off" method="post">
        <div class="form-group">
            <input type="password" autofocus class="form-control small-form" placeholder="Password" id="password" name="password" required>
            <div class="invalid-feedback">Please enter your password</div>
        </div>
        <div class="form-group">
            <input type="password" class="form-control small-form" placeholder="New Password" id="new_password" name="new_password" required>
            <div class="invalid-feedback">Please enter a new password</div>
        </div>
        <div class="form-group">
            <input type="password" class="form-control small-form" placeholder="New Password (again)" id="confirmation" name="confirmation" required>
            <div class="invalid-feedback">Please confirm your password</div>
        </div>
        <button class="btn btn-primary" type="submit">Change</button>
    </form>
    <div class="alert alert-info my-5" role="alert">
      Password must be longer than 6 characters and contain upper and lower case letters and and/or numbers and/or symbols.
    </div>
<script>
    let old_password = document.querySelector("#password");
    let password = document.querySelector("#new_password");
    let confirmation = document.querySelector("#confirmation");
    document.querySelector("#form").onsubmit = function() {
    if(password.value != "" && password.value == confirmation.value) {
              if(password.value.length < 6) {
                alert("Password must be longer than 6 characters.");
                password.focus();
                password.classList.add("is-invalid");
                password.style.borderColor = "#dc3545";
                return false;
              }
              if(password.value == old_password.value) {
                alert("Error: Password must be different from old password!");
                password.focus();
                password.classList.add("is-invalid");
                password.style.borderColor = "#dc3545";
                return false;
              }
              re = /[0-9]/;
              if(!re.test(password.value)) {
                alert("Error: password must contain at least one number (0-9)!");
                password.focus();
                password.classList.add("is-invalid");
                password.style.borderColor = "#dc3545";
                return false;
              }
              re = /[a-z]/;
              if(!re.test(password.value)) {
                alert("Error: password must contain at least one lowercase letter (a-z)!");
                password.focus();
                password.classList.add("is-invalid");
                password.style.borderColor = "#dc3545";
                return false;
              }
              re = /[A-Z]/;
              if(!re.test(password.value)) {
                alert("Error: password must contain at least one uppercase letter (A-Z)!");
                password.focus();
                password.classList.add("is-invalid");
                password.style.borderColor = "#dc3545";
                return false;
              }
    }
    else {
        alert("Error: Please check that you've entered and confirmed your password!");
        password.focus();
        confirmation.classList.add("is-invalid");
        confirmation.style.borderColor = "#dc3545";
        return false;
    }

}
</script>
{% endblock %}

templates/diary_page.html
{% extends 'layout.html' %}
 
{% block title %}
    {{ diary['date'] }}
{% endblock %}

{% block main %}
        <div class ="diary p-5 m-3">

        <!-- Title -->
        <h1>{{ diary['title'] }}</h1>
        <p class="lead">
            by
            <a href="{{ url_for('profile', username=username) }}">{{ username }}</a>
            <form action="{{ url_for('diary.download_diary') }}" method="post">
              <input type="hidden" name="username" value="{{ username }}">
              <input type="hidden" name="date" value="{{ diary['date'] }}">
              <button class="btn btn-primary" type="submit">Download</button>
          </form>
          </p>
        <hr>

        <!-- Date/Time -->
            <h4>{{ diary['date']|date_format }}</h4>
        <p>That day was {{ diary['rating'] }}.</p>

        <hr>
        <!-- Post Content -->
        <div style="text-align: left;">
        {{ diary['diary']|clean_markdown|safe }}
      </div>
      </div>
{% endblock %}

templates/error.html
{% extends "layout.html" %}

{% block title %}
    Error!
{% endblock %}

{% block main %}
<div class="alert alert-danger" role="alert">
    {{ message }}
</div>
{% endblock %}

templates/feedback.html
{% extends "layout.html" %}

{% block title %}

Feedback

{% endblock %}

{% block main %}

<form class="needs-validation" novalidate action="/feedback" autocomplete="off" method="post">
    <div class="form-group">
        <select class="custom-select form-control small-form" name="type" required>
            <option value="" disabled selected>Type</option>
            <option value="bug">Bug</option>
            <option value="suggestion">Suggestion</option>
        </select>
        <div class="invalid-feedback">Please select feedback type</div>
    </div>
    <div class="form-group">
        <input type="email" class="form-control small-form" placeholder="Email" name="email" required>
        <div class="invalid-feedback">Please enter your email</div>
    </div>
    <div class="mb-3">
        <textarea class="form-control small-form" placeholder="Feedback" name="feedback" required></textarea>
        <div class="invalid-feedback">Please write your feedback</div>
    </div>
    <button class="btn btn-primary" type="submit">Send Feedback</button>
</form>

{% endblock %}

templates/index.html
{% extends "layout.html" %}

{% block title %}
Home
{% endblock %}

{% block head %}
<div class="jumbotron text-center" style="display: block;">
    <h1 class="display-4">Welcome!</h1>
    <p class="lead">Here you can write your diaries!</p>
  </div>
{% endblock %}
{% block main %}

    <div class="container p-5">
        <h4>Write your diary in text/md</h4>
        <form class="needs-validation" id="submit_diary" action="{{ url_for('diary.add_diary') }}" novalidate autocomplete="off" method="post">
            <div class="form-group mb-2">
                <input autocomplete="off" autofocus class="form-control small-form" name="title" placeholder="Title of the day" type="text">
            </div>
            <div class="form-group">
                <select class="custom-select form-control small-form" name="rating" required>
                    <option value="" disabled selected>How was your day?</option>
                    <option value="amazing">Amazing</option>
                    <option value="good">Good</option>
                    <option value="average">Average</option>
                    <option value="bad">Bad</option>
                    <option value="terrible">Terrible</option>
                </select>
                <div class="invalid-feedback">Please select how your day was.</div>
            </div>
            <div class="mb-3">
                <textarea class="form-control" placeholder="So, what happened today?" name="diary" required></textarea>
                <div class="invalid-feedback">Please write your diary.</div>
    </div>
        <button class="btn btn-primary" type="submit">Save</button>
        <input type="hidden" name="today_date" value="">
    </form>

    </div>
<script src="/static/validation.js"></script>
<script>
    let d = new Date();
    let today_date = d.getFullYear().toString() + '-' + (d.getMonth() + 1).toString() + '-' + d.getDate().toString();

    document.querySelector("#submit_diary").onsubmit = function () {
        document.querySelector("input[name='today_date']").value = today_date;
        return true;
    }
</script>
{% endblock %}

templates/layout.html
<!DOCTYPE html>

<html lang="en">

<head>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- documentation at http://getbootstrap.com/docs/4.1/, alternative themes at https://bootswatch.com/ -->
    <link href="/static/lux_bootstrap.min.css" rel="stylesheet">

    <link href="/static/logo.png" rel="icon">

    <link href="/static/styles.css" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>

    <title>{% block title %}{% endblock %}</title>

</head>

<body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <a class="navbar-brand" href="/">
            <img src="/static/logo.png" width="30" height="30" alt="">
My Diary
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            {% if session.user_id %}
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active"><a class="nav-link" href="{{ url_for('diary.public_diaries') }}">Public Diaries</a></li>
                <li class="nav-item active"><a class="nav-link" href="{{ url_for('profile', username=session['username']) }}">Profile</a></li>
                <li class="nav-item dropdown active">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown2" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      Settings
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown2">
                        <a class="dropdown-item" href="{{ url_for('settings.change_visibility')}}">Change Visibility</a>
                        <a class="dropdown-item" href="{{ url_for('settings.change_email')}}">Change Email</a>
                        <a class="dropdown-item" href="{{ url_for('settings.change_password')}}">Change Password</a>
                        <div class="dropdown-divider"></div>
                      <a class="dropdown-item" href="/feedback">Send Feedback</a>
                    </div>
                  </li>
                  <li class="nav-item"><a class="nav-link" href="/logout">Log Out</a></li>
            </ul>
            <form class="form-inline my-2 my-lg-0" action="/search" method="get">
                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search your diaries" name="q"
                    required>
                <button class="btn btn-outline-light my-2 my-sm-0" type="submit">Search</button>
            </form>
            {% else %}
            <ul class="navbar-nav ml-auto">
                <li class="nav-item"><a class="nav-link" href="/register">Register</a></li>
                <li class="nav-item"><a class="nav-link" href="/login">Log In</a></li>
            </ul>
            {% endif %}
        </div>
    </nav>
    {% if get_flashed_messages() %}
    <header>
        <div class="alert alert-primary border text-center" role="alert">
            {{ get_flashed_messages() | join(" ") }}
        </div>
    </header>
    {% endif %}
    {% block head %} {% endblock %}
    <main class="container py-5">
        {% block main %}{% endblock %}
    </main>
    <footer>
        My Diary
        <div id="feedback">
            Having any problems? <a href="/feedback" style="text-decoration: underline; color: blue">Tell us what's wrong</a>.
        </div>
    </footer>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
    </body>
</html>

templates/login.html
{% extends "layout.html" %}

{% block title %}
    Log In
{% endblock %}
{% block head %}
<div class="jumbotron text-center">
    <h1 class="display-4">Welcome to MY Diary!</h1>
    <p class="lead">Please log in, if you don't have an account you can <a href="/register" style="text-decoration: underline; color: blue">register</a>.</p>
</div>
{% endblock %}
{% block main %}
    <form class="needs-validation" novalidate action="/login" method="post">
        <div class="form-group mb-2">
            <input autocomplete="off" autofocus class="form-control small-form" name="username" placeholder="Username" type="text" required>
                    <div class="invalid-feedback">Please enter your username</div>
        </div>
        <div class="form-group mb-2">
            <input class="form-control small-form" name="password" placeholder="Password" type="password" required>
                    <div class="invalid-feedback">Please enter password</div>

        </div>
        <button class="btn btn-primary" type="submit">Log In</button>
    </form>

{% endblock %}

templates/profile.html
{% extends "layout.html" %}

{% block title %}
{{ info['username'] }}
{% endblock %}

{% block head %}
<div class="jumbotron jumbotron-fluid text-center">
    <div class="container">
        <h1 class="display-4">{{ info['username'] }}</h1>
        <p class="lead">Email:
            {{ info['email'] }}
            <br>
            Account created on: {{ info['registeration'] }}
            <br>
            Visibility: {% if info['visibility'] == '0' %}
                            Private.
                        {% else %}
                            Public.
                        {% endif %}
        </p>
    </div>
</div>
{% endblock %}

{% block main %}

{% if diaries %}
    {% for diary in diaries %}
        <a href=" {{ url_for('diary.diary_page', username=info['username'], date=diary['date']) }}">
            <div class="alert alert-primary" role="alert">
                <h4 class="alert-heading">{{ diary['date'] }}</h4>
                
                <p>{{ diary['title'] }}, that day was <span class="rating">{{ diary['rating'] }}</span></p>       
            </div>
        </a>
    {% endfor %}
{% else %}
    <div class="alert alert-primary" role="alert">
        You didn't write any diaries.
    </div>
{% endif %}
{% endblock %}

templates/public_diaries.html
{% extends "layout.html" %}

{% block title %}
Public Diaries
{% endblock %}

{% block head %}
<div class="jumbotron jumbotron-fluid text-center">
    <div class="container">
        <h1 class="display-4">Results</h1>
        <p class="lead">Number of results: {{ diaries|length }}</p>
    </div>
</div>
{% endblock %}
{% block main %}
{% if diaries %}
    {% for diary in diaries %}
        <a href=" {{ url_for('diary.diary_page', username=diary['username'], date=diary['date']) }}">
            <div class="alert alert-primary" role="alert">
                <h4 class="alert-heading">{{ diary['date'] }}</h4>
                <p>
                    {{ diary['title'] }}, that day was <span class="rating">{{ diary['rating'] }}</span>
                    <br>
                    by <a href="{{ url_for('profile', username=diary['username']) }}">{{ diary['username'] }}</a>.
                </p>       
            </div>
        </a>
    {% endfor %}

{% else %}
    <div class="alert alert-danger" role="alert">
            No diaries found.
    </div>
{% endif %}

{% endblock %}

templates/register.html
{% extends "layout.html" %}

{% block title %}

Register

{% endblock %}

{% block main %}

<form class="needs-validation" novalidate action="/register" autocomplete="off" method="post">
    <div class="form-group">
        <input type="text" autofocus class="form-control small-form" id="username" placeholder="Username" name="username" required>
        <div class="invalid-feedback">Please enter your username</div>
    </div>
    <div class="form-group">
        <input type="email" class="form-control small-form" id="email" placeholder="Email" name="email" required>
        <div class="invalid-feedback">Please enter your email</div>
    </div>
    <div class="form-group">
        <input type="password" class="form-control small-form" id="password" placeholder="Password" name="password" required>
        <div class="invalid-feedback">Please enter your password</div>
    </div>
    <div class="form-group">
        <input type="password" class="form-control small-form" id="confirmation" placeholder="Password (again)" name="confirmation"
            required>
        <div class="invalid-feedback">Please confirm your password</div>
    </div>
    <button class="btn btn-primary" type="submit">Register</button>
</form>
<div class="alert alert-info my-5" role="alert">
        Username mustn't contain spaces or symbols except for _
        <br>
        Password must be longer than 6 characters and contain upper and lower case letters and and/or numbers and/or symbols. 
      </div>
<script src="/static/register.js">
</script>


{% endblock %}

templates/results.html
{% extends "layout.html" %}

{% block title %}
Results
{% endblock %}

{% block head %}
<div class="jumbotron jumbotron-fluid text-center">
    <div class="container">
        <h1 class="display-4">Results</h1>
        <p class="lead">Number of results: {{ diaries|length }}</p>
    </div>
</div>
{% endblock %}
{% block main %}
{% if diaries %}
    {% for diary in diaries %}
        <a href=" {{ url_for('diary_page', username=session['username'], date=diary['date']) }}">
            <div class="alert alert-primary" role="alert">
                <h4 class="alert-heading">{{ diary['date'] }}</h4>
                <p>{{ diary['title'] }}, that day was <span class="rating">{{ diary['rating'] }}</span></p>       
            </div>
        </a>
    {% endfor %}

{% else %}
    <div class="alert alert-danger" role="alert">
            <h4 class="alert-heading">Error!</h4>
            <p>No results found.</p>
    </div>
{% endif %}

{% endblock %}